### PR TITLE
Poetry

### PR DESCRIPTION
**Pull request by rkhabbaz**

### CODE REVIEW

**Comment by rkhabbaz** [comment]
@trylle @valerii-martell  I was not sure which trigger to use for sphinx doc. I used the same I am using for linting, formatting, and testing. Shall we use a different one? Maybe something to be triggered after approval?

**Comment by trylle** [comment]
> @trylle @valerii-martell I was not sure which trigger to use for sphinx doc. I used the same I am using for linting, formatting, and testing. Shall we use a different one? Maybe something to be triggered after approval?

Wouldn't it make sense to run the documentation publish on every push to trunk, like the original workflow did? I think that's what we want to keep the documentation in sync with.

**Comment by rkhabbaz** [comment]
> > @trylle @valerii-martell I was not sure which trigger to use for sphinx doc. I used the same I am using for linting, formatting, and testing. Shall we use a different one? Maybe something to be triggered after approval?
> 
> Wouldn't it make sense to run the documentation publish on every push to trunk, like the original workflow did? I think that's what we want to keep the documentation in sync with.

What we had was `workflow_dispatch` which is manual trigger. If we would like to keep documentation updated then snippet I suggested will trigger the action when PR is merged into main. Shall I implement it?

**Comment by trylle** [comment]
> What we had was `workflow_dispatch` which is manual trigger. If we would like to keep documentation updated then snippet I suggested will trigger the action when PR is merged into main. Shall I implement it?

Correct me if I'm wrong, but the original workflow trigger events were specified as:
```yaml
on:
  workflow_dispatch:
  push:
    branches:
    - 'main'
```
Which means it runs automatically on push to main, as well as can be triggered manually. I think these are the more conventional events to use rather than the specialized pull request ones. The PR ones will not catch e.g. manual/force pushes, in the rare occurrence that we have to do it.

**Comment by rkhabbaz** [comment]
> > What we had was `workflow_dispatch` which is manual trigger. If we would like to keep documentation updated then snippet I suggested will trigger the action when PR is merged into main. Shall I implement it?
> 
> Correct me if I'm wrong, but the original workflow trigger events were specified as:
> 
> ```yaml
> on:
>   workflow_dispatch:
>   push:
>     branches:
>     - 'main'
> ```
> 
> Which means it runs automatically on push to main, as well as can be triggered manually. I think these are the more conventional events to use rather than the specialized pull request ones. The PR ones will not catch e.g. manual/force pushes, in the rare occurrence that we have to do it.

Makes sense. Reverted back to the original trigger.

**Comment by trylle** [comment]
I don't see any `poetry.lock` file - did you forget to check this in?

**Comment by rkhabbaz** [comment]
> I don't see any `poetry.lock` file - did you forget to check this in?

No, I did not forget it. I did not check it in because `pyproject.toml` is enough for a correct build and `poetry.lock` is a reference to one successful build. I thought not checking it in allows for correct build for different operating system and python versions.

**Comment by trylle** [comment]
> > I don't see any `poetry.lock` file - did you forget to check this in?
> 
> No, I did not forget it. I did not check it in because `pyproject.toml` is enough for a correct build and `poetry.lock` is a reference to one successful build. I thought not checking it in allows for correct build for different operating system and python versions.

The `poetry.lock` file must be checked in, otherwise there is no way to enforce secure and reproducible installs. This is also the recommendation by Poetry: https://python-poetry.org/docs/basic-usage/#installing-without-poetrylock. They leave some wiggle-room with regards to libraries, but since these are all internally developed, we will keep them in sync ourselves, see the thread on Slack.

The lock file contains hashed references to all architectures and runtimes supported by that version, so there should not be any issue there.

**Comment by rkhabbaz** [comment]
> > > I don't see any `poetry.lock` file - did you forget to check this in?
> > 
> > 
> > No, I did not forget it. I did not check it in because `pyproject.toml` is enough for a correct build and `poetry.lock` is a reference to one successful build. I thought not checking it in allows for correct build for different operating system and python versions.
> 
> The `poetry.lock` file must be checked in, otherwise there is no way to enforce secure and reproducible installs. This is also the recommendation by Poetry: https://python-poetry.org/docs/basic-usage/#installing-without-poetrylock. They leave some wiggle-room with regards to libraries, but since these are all internally developed, we will keep them in sync ourselves, see the thread on Slack.
> 
> The lock file contains hashed references to all architectures and runtimes supported by that version of the dependency, so there should not be any issue there.

checked it in

**Review by trylle — APPROVED** [review]

**Review by valerii-martell — APPROVED** [review]

**Pull request merged**
